language: python
os:
  - linux
  - osx

python:
  - "3.6"
  - "3.5"
  - "3.7"
install:
  - bash install/user_install.sh
script: 
  - touch scrape_test.py
  - cat "from science_access.crawl import *" >> scrape_test.py
  - cat "scholar_link=str('https://duckduckgo.com/?q=%21scholar')+str("ninkum")+str('&va=z&t=hc')" >> scrape_test.py
  - cat "follow_links = collect_pubs(scholar_link)" >> scrape_test.py
  - python3 scrape_test.py
  - streamlit run app.py
after_success:
  - coveralls
