os:
  - linux 
  - osx
language: python
python:
  - "3.6"
  - "3.5"
  - "3.7"

install:
  - pip install -r requirements.txt
  - python setup.py install 
  script: 
  - python3 unit_test/scrape_test.py
after_success:
  - coveralls
