language: python
os:
  - linux
  - osx

python:
  - "3.6"
  - "3.5"
  - "3.7"
install:
  - bash install/user_install.sh
  - sudo pip3 install -e .
script: 
  - python3 unit_test/scrape_test.py
  - streamlit run app.py
after_success:
  - coveralls
