version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache

      - run: 
          name: "Setup custom environment variables"
          command: echo 'export MY_ENV_VAR="CIRCLE"' >> $BASH_ENV
      - run: # print the name of the branch we're on
          command: echo ${CIRCLE_BRANCH}
          name: "What branch am I on?"
      - run:      
          name: install
          command: sudo bash install/gecko_install.sh; sudo pip install -r requirements.txt;
      - run: 
          name: more install
          command: sudo python setup.py install; 
      - run: 
          name: test install0
          command: streamlit --version
      - run: 
          name: test install1
          command: python science_access/scrape.py
      - run: 
          name: test install2
          command: python unit_test/test_scrape.py

workflows:
  main:
    jobs:
      - build-and-test
