version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache

      - run:
          name: "Setup custom environment variables"
          command: echo 'export MY_ENV_VAR="CIRCLE"' >> $BASH_ENV
      - run: # print the name of the branch we're on

          name: "What branch am I on?"
          command: echo ${CIRCLE_BRANCH}

      - run:
          name: more install
          command:  sudo pip install nltk; sudo python setup.py install;
      - run:
          name: install coveralls
          command: pip install coverage


  build-docker:
    machine: true
    steps:
      - checkout

      - run: docker build -t wcp .
      - run: docker run -d -p 127.0.0.1:80:80 --name wcp wcp
      - run: docker ps | grep -q wcp
workflows:
  main:
    jobs:
      - build-and-test
